### ISSUE TITLE
I have this error when generating data

### ISSUE THREAD

**Issue by Johnx69** [GenSim2/GenSim2#1]
<img width="1500" alt="Screenshot 2024-10-12 at 01 36 44" src="https://github.com/user-attachments/assets/72f8cd97-d37d-41d6-bbb9-fc3dc4058f1b">

**Comment by liruiw** [comment]
Thanks for the catch here. The generation process can have failures. I wonder how frequently this happens.  @piao-0429 feel free to take a look at this as well?

**Comment by piao-0429** [comment]
Thanks for your interest in our project! Unfortunately, I didn't meet with this deprecation error before, but I noticed that as mentioned in the [[OpenAi platform doc](https://platform.openai.com/docs/deprecations)](https://platform.openai.com/docs/deprecations), some models may be inaccessible. You can try to replace the "gpt-4-vision-preview" with other latest visual models, such as "gpt-4-turbo". We have already updated the corresponding config to use the latest GPT models. Also, there may be some problems if you are not using the matched version of the openai package. Please check if the version is `0.28.0` by `pip list | grep openai`, and if not, please reinstall it by `pip install openai==0.28.0`.
