### ISSUE TITLE
Can we apply this process of work on issac sim simulation to generate python code?

### ISSUE THREAD

**Issue by anhdao69** [GenSim2/GenSim2#4]
Hi Gensim2 author, thank you for a great work. I just wonder whether I can apply this process into generate data in issac sim or not? I have never been touched issac sim before. 

Thank you very much!

**Comment by liruiw** [comment]
Thanks for your interests! This is definitely possible as Isaac Sim is one of our simulators in experiments as well. If you look at the codebase jere https://github.com/GenSim2/GenSim2/tree/master/gensim2/env/base, most of the codes are simulators-independent. So it's possible to inherit these classes to use Isaac Sim.
