### ISSUE TITLE
Release data

### ISSUE THREAD

**Issue by peryion** [GenSim2/GenSim2#5]
Hello @piao-0429 👋,

Thank you for sharing your amazing work! I found your paper incredibly insightful and am particularly interested in the data used in your research. I was wondering if you have any plans to release the dataset mentioned in your paper, or if it might become available in the future?

Looking forward to your response. Thank you again for your contributions!

**Comment by piao-0429** [comment]
Thanks for your appreciation! We are still working on the model training part, but we plan to release both dataset and pre-trained models in the near future.
