### ISSUE TITLE
sapine's rendering error

### ISSUE THREAD

**Issue by dfgan** [GenSim2/GenSim2#6]
Hi, thanks for the open source, I'm having some problems setting up the environment to use it I hope you can help me out. I started to install sapine version 2.2.2 according to the requirements, but the runtime will be render error, and then installed mani-skill, although the render problem is solved, but sapine was forced to upgrade to 3.0.0, which is a lot of interfaces in the project will not be compatible, may I ask you how to solve it?

**Comment by liruiw** [comment]
I believe the codebase is only tested with sapien 2 not 3. This might be a question that can ask in the Sapien github issue.

**Comment by AnnabellaMacaluso** [comment]
What are the specific rendering issues? I can try to refer you to the proper troubleshooting guides. Some of the sapien 3.0.0/maniskill rendering troubleshooting also applies to Sapien 2.2.2. We only used Sapien 2.2.2 in testing.
